services:
  users-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - users-data-test:/var/lib/postgresql/data
    networks:
      - usersnetwork
networks:
  usersnetwork:

volumes:
  users-data-test:
